import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "./TrpcProver";
import { Toaster } from "@/components/ui/Sonner";
import { ThemeProvider } from "@/app/dashboard/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="data-theme" defaultTheme="system" enableSystem>
                    <Toaster />
                    <TRPCProvider>{children}</TRPCProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
